# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
job:
  url:     /job
  class:   sfDoctrineRouteCollection
  options: { model: JobeetJob}

job_show_user:
  url:   /job/:company_slug/:location_slug/:id/:position_slug
  class : sfDoctrineRoute
  options: {model: JobeetJob, type: object }
  param: { module: job, action: show }
  requirements:
    id: \d+


# generic rules
# please, remove them by adding more specific rules

#homepage:
#  url:   /
#  param: { module: job, action: index }

#default:
#  url:   /:module/:action/*
